SELECT FIRST_NAME , SALARY FROM Worker;

SELECT 44+11;
SELECT now();

SELECT lcase('TANVI');

SELECT * FROM Worker;
SELECT * FROM Worker WHERE SALARY > 80000;
SELECT * FROM Worker WHERE DEPARTMENT= 'HR';
SELECT * FROM Worker WHERE SALARY between 80000 AND 300000;
-- reduce OR statements
-- HR, ADMIN BOTH
SELECT * FROM Worker WHERE DEPARTMENT = 'HR' OR DEPARTMENT ='ADMIN';

-- better way is to use IN  keyword
SELECT * FROM Worker WHERE DEPARTMENT IN('HR'); 

SELECT * FROM Worker WHERE DEPARTMENT NOT IN('HR','ADMIN');


